"""extend coach_insights behavioral memory fields (Wave-2 H1G2)

Revision ID: 0db7cfbb706f
Revises: 9558e190f209
Create Date: 2026-05-10 03:22:36.542251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0db7cfbb706f'
down_revision: Union[str, None] = '9558e190f209'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coach_insights', schema=None) as batch_op:
        batch_op.add_column(sa.Column('insight_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('title', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('confidence_basis', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('source_refs', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('evidence_count', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('counter_evidence_count', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('last_evidence_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_counter_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('activated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_seen_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('para_category', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('archived_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('archived_reason', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('sort_priority', sa.Integer(), server_default='5', nullable=False))
        batch_op.create_unique_constraint('uq_insights_type_title', ['user_id', 'insight_type', 'title'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coach_insights', schema=None) as batch_op:
        batch_op.drop_constraint('uq_insights_type_title', type_='unique')
        batch_op.drop_column('sort_priority')
        batch_op.drop_column('archived_reason')
        batch_op.drop_column('archived_at')
        batch_op.drop_column('para_category')
        batch_op.drop_column('last_seen_at')
        batch_op.drop_column('activated_at')
        batch_op.drop_column('status')
        batch_op.drop_column('last_counter_at')
        batch_op.drop_column('last_evidence_at')
        batch_op.drop_column('counter_evidence_count')
        batch_op.drop_column('evidence_count')
        batch_op.drop_column('source_refs')
        batch_op.drop_column('confidence_basis')
        batch_op.drop_column('title')
        batch_op.drop_column('insight_type')

    # ### end Alembic commands ###
