"""add coach_insights and decision_journal tables

Revision ID: 12b80d6485bf
Revises: 62136ecd252e
Create Date: 2026-05-10 02:53:13.581043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12b80d6485bf'
down_revision: Union[str, None] = '62136ecd252e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
