"""add reasoning_traces table (Wave-2 H1G3)

Revision ID: 53a3257f906c
Revises: 0db7cfbb706f
Create Date: 2026-05-10 14:12:49.038575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53a3257f906c'
down_revision: Union[str, None] = '0db7cfbb706f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reasoning_traces',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('trace_id', sa.String(length=36), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('parent_step_id', sa.Integer(), nullable=True),
    sa.Column('coach_memory_id', sa.Integer(), nullable=True),
    sa.Column('operation_name', sa.Enum('RULE_CHECK', 'LLM_CALL', 'EXECUTE_TOOL', 'OBSERVATION', 'FINAL_ANSWER', name='operationname'), nullable=False),
    sa.Column('intent', sa.Text(), nullable=True),
    sa.Column('action_input_json', sa.Text(), nullable=True),
    sa.Column('observation', sa.Text(), nullable=True),
    sa.Column('inference', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('provider_system', sa.String(length=50), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('usage_input_tokens', sa.Integer(), nullable=True),
    sa.Column('usage_output_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['coach_memory_id'], ['coach_memories.id'], ),
    sa.ForeignKeyConstraint(['parent_step_id'], ['reasoning_traces.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reasoning_traces', schema=None) as batch_op:
        batch_op.create_index('ix_reasoning_traces_coach_memory_id', ['coach_memory_id'], unique=False)
        batch_op.create_index('ix_reasoning_traces_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_reasoning_traces_trace_id_step_index', ['trace_id', 'step_index'], unique=False)
        batch_op.create_index('ix_reasoning_traces_user_id', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reasoning_traces', schema=None) as batch_op:
        batch_op.drop_index('ix_reasoning_traces_user_id')
        batch_op.drop_index('ix_reasoning_traces_trace_id_step_index')
        batch_op.drop_index('ix_reasoning_traces_created_at')
        batch_op.drop_index('ix_reasoning_traces_coach_memory_id')

    op.drop_table('reasoning_traces')
    # ### end Alembic commands ###
