"""add price_history table

Revision ID: 62136ecd252e
Revises: fa46373f4ca8
Create Date: 2026-05-09 13:31:13.654027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62136ecd252e'
down_revision: Union[str, None] = 'fa46373f4ca8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_history',
    sa.Column('fund_code', sa.String(length=20), nullable=False),
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.Column('source', sa.Enum('tefas', 'manual', 'yfinance', 'isyatirim', name='pricesource'), nullable=False),
    sa.Column('close_price', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('fund_code', 'price_date', 'source', name='pk_price_history')
    )
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.create_index('ix_price_history_fund_date', ['fund_code', 'price_date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.drop_index('ix_price_history_fund_date')

    op.drop_table('price_history')
    # ### end Alembic commands ###
