"""add decision_journal table (Wave-2 H1G1 part 2)

Revision ID: 9558e190f209
Revises: 12b80d6485bf
Create Date: 2026-05-10 02:57:06.831677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9558e190f209'
down_revision: Union[str, None] = '12b80d6485bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decision_journal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('decision_text', sa.Text(), nullable=False),
    sa.Column('decision_type', sa.String(length=40), nullable=True),
    sa.Column('related_action_id', sa.Integer(), nullable=True),
    sa.Column('predicted_outcome', sa.Text(), nullable=True),
    sa.Column('confidence_at_decision', sa.Integer(), nullable=True),
    sa.Column('mc_rules_applied', sa.Text(), nullable=True),
    sa.Column('cockpit_snapshot_hash', sa.String(length=64), nullable=True),
    sa.Column('premortem_scenarios', sa.Text(), nullable=True),
    sa.Column('premortem_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_outcome', sa.Text(), nullable=True),
    sa.Column('outcome_evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outcome_score', sa.Integer(), nullable=True),
    sa.Column('lessons_learned', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('para_category', sa.String(length=20), server_default='project', nullable=False),
    sa.ForeignKeyConstraint(['related_action_id'], ['action_history.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('decision_journal', schema=None) as batch_op:
        batch_op.create_index('idx_decision_journal_pending_eval', ['user_id'], unique=False, sqlite_where=sa.text('outcome_evaluated_at IS NULL'))
        batch_op.create_index('idx_decision_journal_user_time', ['user_id', 'decided_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_decision_journal_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_decision_journal_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('decision_journal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_decision_journal_user_id'))
        batch_op.drop_index(batch_op.f('ix_decision_journal_id'))
        batch_op.drop_index('idx_decision_journal_user_time')
        batch_op.drop_index('idx_decision_journal_pending_eval', sqlite_where=sa.text('outcome_evaluated_at IS NULL'))

    op.drop_table('decision_journal')
    # ### end Alembic commands ###
