"""genesis_full_schema

Revision ID: b70779a2f621
Revises: fec73e5343e5
Create Date: 2026-07-12 14:57:29.402282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b70779a2f621'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_history',
    sa.Column('fund_code', sa.String(length=20), nullable=False),
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.Column('source', sa.Enum('tefas', 'manual', 'yfinance', 'isyatirim', name='pricesource'), nullable=False),
    sa.Column('close_price', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('fund_code', 'price_date', 'source', name='pk_price_history')
    )
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.create_index('ix_price_history_fund_date', ['fund_code', 'price_date'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('account_type', sa.Enum('cash', 'credit_card', 'loan', 'investment', name='accounttype'), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('credit_limit', sa.Float(), nullable=True),
    sa.Column('statement_day', sa.Integer(), nullable=True),
    sa.Column('payment_day', sa.Integer(), nullable=True),
    sa.Column('interest_rate', sa.Float(), nullable=True),
    sa.Column('monthly_payment', sa.Float(), nullable=True),
    sa.Column('remaining_installments', sa.Integer(), nullable=True),
    sa.Column('next_payment_date', sa.Date(), nullable=True),
    sa.Column('fund_code', sa.String(length=20), nullable=True),
    sa.Column('lot_count', sa.Float(), nullable=True),
    sa.Column('cost_per_lot', sa.Float(), nullable=True),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('last_price_update', sa.DateTime(), nullable=True),
    sa.Column('is_emanet', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounts_id'), ['id'], unique=False)
        batch_op.create_index('ix_accounts_user_type', ['user_id', 'account_type'], unique=False)

    op.create_table('api_call_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('success', 'failed', 'rate_limited', name='apicallstatus'), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('tool_calls_count', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('called_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_call_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_call_log_id'), ['id'], unique=False)
        batch_op.create_index('ix_api_calls_user_called', ['user_id', 'called_at'], unique=False)
        batch_op.create_index('ix_api_calls_user_provider_called', ['user_id', 'provider', 'called_at'], unique=False)

    op.create_table('coach_memories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tool_calls_json', sa.Text(), nullable=True),
    sa.Column('tool_call_id', sa.String(length=64), nullable=True),
    sa.Column('pending_action_ids_json', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('coach_memories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coach_memories_id'), ['id'], unique=False)
        batch_op.create_index('ix_memories_user_timestamp', ['user_id', 'timestamp'], unique=False)

    op.create_table('envelopes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('monthly_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'category', name='uq_envelope_user_category')
    )
    with op.batch_alter_table('envelopes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_envelopes_id'), ['id'], unique=False)

    op.create_table('goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goal_type', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('target_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('baseline_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('progress_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('projected_completion_date', sa.Date(), nullable=True),
    sa.Column('last_refreshed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('achieved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.create_index('ix_goals_goal_type', ['goal_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_goals_id'), ['id'], unique=False)
        batch_op.create_index('ix_goals_status', ['status'], unique=False)

    op.create_table('master_checkpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('checkpoint_type', sa.Enum('red_line', 'strategy', 'rule', 'context', name='checkpointtype'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('master_checkpoints', schema=None) as batch_op:
        batch_op.create_index('ix_checkpoints_user_active_priority', ['user_id', 'is_active', 'priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_checkpoints_id'), ['id'], unique=False)

    op.create_table('net_worth_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('net_worth_seen', sa.Float(), nullable=False),
    sa.Column('net_worth_full', sa.Float(), nullable=False),
    sa.Column('cash', sa.Float(), nullable=False),
    sa.Column('card_debt', sa.Float(), nullable=False),
    sa.Column('loan_debt', sa.Float(), nullable=False),
    sa.Column('investment_value', sa.Float(), nullable=False),
    sa.Column('receivables', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'snapshot_date', name='uq_nws_user_date')
    )
    with op.batch_alter_table('net_worth_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_net_worth_snapshots_id'), ['id'], unique=False)
        batch_op.create_index('ix_nws_user_date', ['user_id', 'snapshot_date'], unique=False)

    op.create_table('pending_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'executed', 'failed', name='actionstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('warning', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('source_recurring_id', sa.Integer(), nullable=True),
    sa.Column('source_recurring_type', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pending_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pending_actions_id'), ['id'], unique=False)
        batch_op.create_index('ix_pending_user_status', ['user_id', 'status'], unique=False)

    op.create_table('personal_debts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('counterparty', sa.String(length=100), nullable=False),
    sa.Column('direction', sa.Enum('receivable', 'payable', name='debtdirection'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('paid_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('personal_debts', schema=None) as batch_op:
        batch_op.create_index('ix_debts_user_due', ['user_id', 'due_date'], unique=False)
        batch_op.create_index('ix_debts_user_paid', ['user_id', 'is_paid'], unique=False)
        batch_op.create_index(batch_op.f('ix_personal_debts_id'), ['id'], unique=False)

    op.create_table('recurring_incomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('day_of_month', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_triggered_year_month', sa.String(length=7), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recurring_incomes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recurring_incomes_id'), ['id'], unique=False)

    op.create_table('wishlist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item', sa.String(length=200), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wishlist_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wishlist_items_id'), ['id'], unique=False)
        batch_op.create_index('ix_wishlist_user_status', ['user_id', 'status'], unique=False)

    op.create_table('action_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('source', sa.Enum('user', 'coach', 'system', name='actionsource'), nullable=False),
    sa.Column('pending_action_id', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('net_worth_before', sa.Float(), nullable=True),
    sa.Column('net_worth_after', sa.Float(), nullable=True),
    sa.Column('cash_before', sa.Float(), nullable=True),
    sa.Column('cash_after', sa.Float(), nullable=True),
    sa.Column('reverted_at', sa.DateTime(), nullable=True),
    sa.Column('reverted_by_action_id', sa.Integer(), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pending_action_id'], ['pending_actions.id'], ),
    sa.ForeignKeyConstraint(['reverted_by_action_id'], ['action_history.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('action_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_action_history_id'), ['id'], unique=False)
        batch_op.create_index('ix_action_history_user_applied', ['user_id', 'applied_at'], unique=False)
        batch_op.create_index('ix_action_history_user_type', ['user_id', 'action_type'], unique=False)

    op.create_table('coach_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.Enum('critical', 'high', 'normal', 'low', name='insightpriority'), nullable=False),
    sa.Column('dedup_key', sa.String(length=80), nullable=True),
    sa.Column('source_message_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_referenced_at', sa.DateTime(), nullable=True),
    sa.Column('insight_type', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('confidence_basis', sa.String(length=30), nullable=True),
    sa.Column('source_refs', sa.Text(), nullable=True),
    sa.Column('evidence_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('counter_evidence_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_evidence_at', sa.DateTime(), nullable=True),
    sa.Column('last_counter_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('para_category', sa.String(length=20), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('archived_reason', sa.String(length=50), nullable=True),
    sa.Column('sort_priority', sa.Integer(), server_default='5', nullable=False),
    sa.ForeignKeyConstraint(['source_message_id'], ['coach_memories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'insight_type', 'title', name='uq_insights_type_title')
    )
    with op.batch_alter_table('coach_insights', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coach_insights_id'), ['id'], unique=False)
        batch_op.create_index('ix_insights_user_active_priority', ['user_id', 'is_active', 'priority'], unique=False)
        batch_op.create_index('uix_insights_user_dedup', ['user_id', 'dedup_key'], unique=True)

    op.create_table('goal_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('criteria', sa.JSON(), nullable=False),
    sa.Column('allocation_type', sa.String(length=20), nullable=False),
    sa.Column('allocation_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('goal_rules', schema=None) as batch_op:
        batch_op.create_index('ix_goal_rules_goal_id', ['goal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_goal_rules_id'), ['id'], unique=False)

    op.create_table('reasoning_traces',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('trace_id', sa.String(length=36), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('parent_step_id', sa.Integer(), nullable=True),
    sa.Column('coach_memory_id', sa.Integer(), nullable=True),
    sa.Column('operation_name', sa.Enum('RULE_CHECK', 'LLM_CALL', 'EXECUTE_TOOL', 'OBSERVATION', 'FINAL_ANSWER', name='operationname'), nullable=False),
    sa.Column('intent', sa.Text(), nullable=True),
    sa.Column('action_input_json', sa.Text(), nullable=True),
    sa.Column('observation', sa.Text(), nullable=True),
    sa.Column('inference', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('provider_system', sa.String(length=50), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('usage_input_tokens', sa.Integer(), nullable=True),
    sa.Column('usage_output_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['coach_memory_id'], ['coach_memories.id'], ),
    sa.ForeignKeyConstraint(['parent_step_id'], ['reasoning_traces.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reasoning_traces', schema=None) as batch_op:
        batch_op.create_index('ix_reasoning_traces_coach_memory_id', ['coach_memory_id'], unique=False)
        batch_op.create_index('ix_reasoning_traces_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_reasoning_traces_trace_id_step_index', ['trace_id', 'step_index'], unique=False)
        batch_op.create_index('ix_reasoning_traces_user_id', ['user_id'], unique=False)

    op.create_table('recurring_expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('day_of_month', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_triggered_year_month', sa.String(length=7), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recurring_expenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recurring_expenses_id'), ['id'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('transaction_type', sa.Enum('income', 'expense', 'transfer', name='transactiontype'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('is_card_expense', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index('ix_transactions_account_date', ['account_id', 'transaction_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_id'), ['id'], unique=False)
        batch_op.create_index('ix_transactions_user_category', ['user_id', 'category'], unique=False)
        batch_op.create_index('ix_transactions_user_date', ['user_id', 'transaction_date'], unique=False)

    op.create_table('decision_journal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('decision_text', sa.Text(), nullable=False),
    sa.Column('decision_type', sa.String(length=40), nullable=True),
    sa.Column('related_action_id', sa.Integer(), nullable=True),
    sa.Column('predicted_outcome', sa.Text(), nullable=True),
    sa.Column('confidence_at_decision', sa.Integer(), nullable=True),
    sa.Column('mc_rules_applied', sa.Text(), nullable=True),
    sa.Column('cockpit_snapshot_hash', sa.String(length=64), nullable=True),
    sa.Column('premortem_scenarios', sa.Text(), nullable=True),
    sa.Column('premortem_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_outcome', sa.Text(), nullable=True),
    sa.Column('outcome_evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outcome_score', sa.Integer(), nullable=True),
    sa.Column('lessons_learned', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('para_category', sa.String(length=20), server_default='project', nullable=False),
    sa.ForeignKeyConstraint(['related_action_id'], ['action_history.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('decision_journal', schema=None) as batch_op:
        batch_op.create_index('idx_decision_journal_pending_eval', ['user_id'], unique=False, sqlite_where=sa.text('outcome_evaluated_at IS NULL'))
        batch_op.create_index('idx_decision_journal_user_time', ['user_id', 'decided_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_decision_journal_id'), ['id'], unique=False)

    op.create_table('goal_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['goal_rules.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('goal_id', 'transaction_id', name='uq_goal_tx')
    )
    with op.batch_alter_table('goal_allocations', schema=None) as batch_op:
        batch_op.create_index('ix_goal_allocations_goal_id', ['goal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_goal_allocations_id'), ['id'], unique=False)
        batch_op.create_index('ix_goal_allocations_transaction_id', ['transaction_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal_allocations', schema=None) as batch_op:
        batch_op.drop_index('ix_goal_allocations_transaction_id')
        batch_op.drop_index(batch_op.f('ix_goal_allocations_id'))
        batch_op.drop_index('ix_goal_allocations_goal_id')

    op.drop_table('goal_allocations')
    with op.batch_alter_table('decision_journal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_decision_journal_id'))
        batch_op.drop_index('idx_decision_journal_user_time')
        batch_op.drop_index('idx_decision_journal_pending_eval', sqlite_where=sa.text('outcome_evaluated_at IS NULL'))

    op.drop_table('decision_journal')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_transactions_user_date')
        batch_op.drop_index('ix_transactions_user_category')
        batch_op.drop_index(batch_op.f('ix_transactions_id'))
        batch_op.drop_index('ix_transactions_account_date')

    op.drop_table('transactions')
    with op.batch_alter_table('recurring_expenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recurring_expenses_id'))

    op.drop_table('recurring_expenses')
    with op.batch_alter_table('reasoning_traces', schema=None) as batch_op:
        batch_op.drop_index('ix_reasoning_traces_user_id')
        batch_op.drop_index('ix_reasoning_traces_trace_id_step_index')
        batch_op.drop_index('ix_reasoning_traces_created_at')
        batch_op.drop_index('ix_reasoning_traces_coach_memory_id')

    op.drop_table('reasoning_traces')
    with op.batch_alter_table('goal_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_goal_rules_id'))
        batch_op.drop_index('ix_goal_rules_goal_id')

    op.drop_table('goal_rules')
    with op.batch_alter_table('coach_insights', schema=None) as batch_op:
        batch_op.drop_index('uix_insights_user_dedup')
        batch_op.drop_index('ix_insights_user_active_priority')
        batch_op.drop_index(batch_op.f('ix_coach_insights_id'))

    op.drop_table('coach_insights')
    with op.batch_alter_table('action_history', schema=None) as batch_op:
        batch_op.drop_index('ix_action_history_user_type')
        batch_op.drop_index('ix_action_history_user_applied')
        batch_op.drop_index(batch_op.f('ix_action_history_id'))

    op.drop_table('action_history')
    with op.batch_alter_table('wishlist_items', schema=None) as batch_op:
        batch_op.drop_index('ix_wishlist_user_status')
        batch_op.drop_index(batch_op.f('ix_wishlist_items_id'))

    op.drop_table('wishlist_items')
    with op.batch_alter_table('recurring_incomes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recurring_incomes_id'))

    op.drop_table('recurring_incomes')
    with op.batch_alter_table('personal_debts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_personal_debts_id'))
        batch_op.drop_index('ix_debts_user_paid')
        batch_op.drop_index('ix_debts_user_due')

    op.drop_table('personal_debts')
    with op.batch_alter_table('pending_actions', schema=None) as batch_op:
        batch_op.drop_index('ix_pending_user_status')
        batch_op.drop_index(batch_op.f('ix_pending_actions_id'))

    op.drop_table('pending_actions')
    with op.batch_alter_table('net_worth_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_nws_user_date')
        batch_op.drop_index(batch_op.f('ix_net_worth_snapshots_id'))

    op.drop_table('net_worth_snapshots')
    with op.batch_alter_table('master_checkpoints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_master_checkpoints_id'))
        batch_op.drop_index('ix_checkpoints_user_active_priority')

    op.drop_table('master_checkpoints')
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.drop_index('ix_goals_status')
        batch_op.drop_index(batch_op.f('ix_goals_id'))
        batch_op.drop_index('ix_goals_goal_type')

    op.drop_table('goals')
    with op.batch_alter_table('envelopes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_envelopes_id'))

    op.drop_table('envelopes')
    with op.batch_alter_table('coach_memories', schema=None) as batch_op:
        batch_op.drop_index('ix_memories_user_timestamp')
        batch_op.drop_index(batch_op.f('ix_coach_memories_id'))

    op.drop_table('coach_memories')
    with op.batch_alter_table('api_call_log', schema=None) as batch_op:
        batch_op.drop_index('ix_api_calls_user_provider_called')
        batch_op.drop_index('ix_api_calls_user_called')
        batch_op.drop_index(batch_op.f('ix_api_call_log_id'))

    op.drop_table('api_call_log')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index('ix_accounts_user_type')
        batch_op.drop_index(batch_op.f('ix_accounts_id'))

    op.drop_table('accounts')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))

    op.drop_table('users')
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.drop_index('ix_price_history_fund_date')

    op.drop_table('price_history')
    # ### end Alembic commands ###
